Animal-Shelter/Models/Animal.cs
using System;
using MySql.Data.MySqlClient;

namespace Animal_Shelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public DateTime AdmitDate { get; set; }
    public string Breed { get; set; }
    public string Type { get; set; }
  }
  // public enum Gender
  // {
  //   Male,
  //   Female,
  //   Other
  // }
}

Animal-Shelter/Models/Animal_ShelterContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace Animal_Shelter.Models
{
  public class Animal_ShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public Animal_ShelterContext(DbContextOptions options) : base(options) { }
  }
}

Animal-Shelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using Animal_Shelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace Animal_Shelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly Animal_ShelterContext _db;
    public AnimalsController(Animal_ShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
      return View(thisAnimal);
    }
  }
}

Animal-Shelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Animal_Shelter.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Animal-Shelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model Animal_Shelter.Models.Animal

<h4>Register an animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)

  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)

  @Html.LabelFor(model => model.Gender)
  @Html.TextBoxFor(model => model.Gender)

  @Html.LabelFor(model => model.AdmitDate)
  @Html.TextBoxFor(model => model.AdmitDate)

  <input type="submit" value="Register an animal" />
}

<p>@Html.ActionLink("Show all animals", "Index")</p>

Animal-Shelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model Animal_Shelter.Models.Animal

<h2></h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)</h3>
<h3>@Html.DisplayNameFor(model => model.AdmitDate): @Html.DisplayFor(model => model.AdmitDate)</h3>
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h3>
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)</h3>
<p></p>@Html.ActionLink("Back to list", "Index")</p>

Animal-Shelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using Animal_Shelter.Models;
@model List<Animal_Shelter.Models.Animal>;

<h1>Animal</h1>

<ul>
  @foreach (Animal animal in Model)
  {
    <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new animal", "Create")</p>

Animal-Shelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Animal Adoption Database!</h1>
<p>@Html.ActionLink("See all Animals", "Index", "Animals")</p>
<p>@Html.ActionLink("Add new Animal", "Create", "Animals")</p>

Animal-Shelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to the Animal Adoption Database!</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>